apiVersion: v1
kind: Namespace
metadata:
  name: team-a
  labels:
    app: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b
  labels:
    app: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-c
  labels:
    app: demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-d
  labels:
    app: demo
---