apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: team-a
  labels:
    app: frontend
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
