apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-04-02
  namespace: ns-04
  labels:
    app: app-04-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-04-02
  template:
    metadata:
      labels:
        app: app-04-02
    spec:
      serviceAccountName: default
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
