apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-06-04
  namespace: ns-06
  labels:
    app: app-06-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-06-04
  template:
    metadata:
      labels:
        app: app-06-04
    spec:
      serviceAccountName: default
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
