apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-08-01
  namespace: ns-08
  labels:
    app: app-08-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-08-01
  template:
    metadata:
      labels:
        app: app-08-01
    spec:
      serviceAccountName: default
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
