apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-ns-01-allow-from-app-01-01-to-app-01-02
  namespace: ns-01
spec:
  podSelector:
    matchLabels:
      app: app-01-02
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: app-01-01
  policyTypes:
  - Ingress
