apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-ns-09-allow-from-app-09-01-to-app-09-02
  namespace: ns-09
spec:
  podSelector:
    matchLabels:
      app: app-09-02
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: app-09-01
  policyTypes:
  - Ingress
