apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-ns-04-allow-from-app-04-01-to-app-04-02
  namespace: ns-04
spec:
  podSelector:
    matchLabels:
      app: app-04-02
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: app-04-01
  policyTypes:
  - Ingress
