apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-ns-03-allow-from-app-03-01-to-app-03-02
  namespace: ns-03
spec:
  podSelector:
    matchLabels:
      app: app-03-02
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: app-03-01
  policyTypes:
  - Ingress
